[package]
name = "tunfetch-wasm"
version = "0.1.0"
edition = "2021"
authors = ["oxcl <oxcl@proton.me>"]
repository = "https://github.com/oxcl/tunfetch"
description = "Drop-in fetch() replacement for Cloudflare Workers with SOCKS5 and HTTP proxy support built with Rust and WASM"
license = "LGPLv3"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22"
bytes = "1"
thiserror = "1"
worker = { version = "0.8" }
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
http = "1"
hyper = { version = "1", default-features = false, features = ["client", "http1"] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio"] }
http-body-util = "0.1"
console_error_panic_hook = "0.1"
js-sys = "0.3"
web-sys = { version = "0.3.103", features = [
    "console",
    "Headers",
    "Response",
    "ResponseInit",
] }
tokio = { version = "1", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "io-util"] }
futures = "0.3"
